# -*- coding: utf-8 -*-
"""Food_Delivery_System_Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CYkFgUjz3yrB1hgTisTYe4VyFjYSvz9D

# Project 3: Food Delivery System

Develop a command-line food delivery system using object-oriented programming in Python.

The system will model customers, delivery partners, restaurants, menu items, and orders. It will support registration, wallet top-up, menu management, order placement, bill calculation, order acceptance, OTP verification, delivery, and user notifications.

Complete the sections in order and run the validation cells after each stage.
"""

#@title Diagram helper { display-mode: "form" }
from IPython.display import HTML, display
import uuid

def show(diagram):
    element_id = "mermaid-" + uuid.uuid4().hex

    display(HTML(f"""
    <div class="mermaid" id="{element_id}">
    {diagram}
    </div>

    <script type="module">
      import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
      mermaid.initialize({{startOnLoad: false, theme: 'neutral'}});
      const element = document.getElementById('{element_id}');
      mermaid.run({{nodes: [element]}});
    </script>
    """))

"""## System Flow

The completed program should follow this sequence.
"""

#@title System flow { display-mode: "form" }
show("""
flowchart LR
    A[Register Customer] --> B[Create Restaurant]
    B --> C[Add Menu Items]
    C --> D[Top Up Wallet]
    D --> E[Place Order]
    E --> F[Calculate Bill]
    F --> G[Accept Order]
    G --> H[Verify OTP]
    H --> I[Deliver Order]
    I --> J[Notify Users]
""")

"""## OOP Recall

Consider a school system.

`Person` can hold information common to people in the school. `Student` and `Teacher` can inherit that common structure. A class register can then store objects created from those classes.

Recreate this structure in the cells below.
"""

# Person, Student and Teacher

# [Code Here]

# Create a class register containing objects

# [Code Here]

"""## Class Design

Complete the table using the project brief before opening the class map.

| Class | Parent class | Attributes | Methods |
|---|---|---|---|
|  |  |  |  |
|  |  |  |  |
|  |  |  |  |
|  |  |  |  |
|  |  |  |  |
|  |  |  |  |

After completing the table, open the class map and compare the structures.
"""

#@title Class map { display-mode: "form" }
show("""
classDiagram
  class User {
    <<abstract>>
    -_name
    -_phone
    -_wallet_balance
    +add_to_wallet(amount)
    +notify(message)*
    +display_profile()*
  }

  class Customer {
    +address
    +order_history
    +place_order(restaurant, items)
  }

  class DeliveryPartner {
    +vehicle
    +is_available
    +rating
    +accept_order(order)
    +deliver(order, otp)
  }

  class MenuItem {
    +name
    +price
    +is_veg
  }

  class Restaurant {
    +name
    +location
    -_menu
    +add_item(menu_item)
    +get_menu()
    +is_open()
  }

  class Order {
    -_order_id
    -_items
    -_status
    -_otp
    +calculate_bill()
    +estimated_time()
    +update_status(new_status)
    +verify_otp(otp)
  }

  User <|-- Customer
  User <|-- DeliveryPartner
  Restaurant o-- MenuItem
  Order o-- MenuItem
  Customer ..> Order : creates
  DeliveryPartner ..> Order : delivers
""")

"""## 1. User

`User` contains the data and behaviour shared by customers and delivery partners.

Keep `User` abstract. `add_to_wallet(amount)` must accept zero or positive values. A negative amount must not change the wallet balance.

### Predict the Output

Before running the statement below, write down what you expect to happen.

```python
u = User("Aman", "9999999999")
```
"""

from abc import ABC, abstractmethod

class User(ABC):

    def __init__(self, name, phone):
        self._name = name
        self._phone = phone
        self._wallet_balance = 0

    def add_to_wallet(self, amount):
        if amount >= 0:
          self._wallet_balance += amount

    @abstractmethod
    def notify(self, message):
        pass

    @abstractmethod
    def display_profile(self):
        pass



"""## 2. Customer

`Customer` inherits from `User`.

Additional data:
- `address`
- `order_history`, initially an empty list

Required behaviour:
- `notify(message)` prints a customer-specific notification.
- `display_profile()` prints the customer name, phone, wallet balance, and address.
- `place_order(restaurant, items)` creates an `Order`, adds it to `order_history`, and returns the created order.
"""

class Customer(User):

    def __init__(self, name, phone, address):
       super().__init__(name,phone)
       self.address = address
       self.order_history = []

    def notify(self, message):
        print("Notificatoin: ",message)

    def display_profile(self):
        print("Name: ", self._name)
        print("Phone: ", self._phone)
        print("Wallet Balance: ", self._wallet_balance)
        print("Address: ", self.address)

    def place_order(self, restaurant, items):
        order = Order(items)
        self.order_history.append(order)
        print("Your OTP is: ",order._otp)

        return order

#@title Validate User and Customer { display-mode: "form" }

def _check_user_customer():
    messages = []

    try:
        User("Aman", "9999999999")
        messages.append("CHECK: User should not be created directly. Keep User abstract.")
    except TypeError:
        messages.append("PASS: User cannot be created directly.")
    except Exception:
        messages.append("CHECK: User creation is failing for a reason other than abstraction.")

    try:
        customer = Customer("Priya", "9876543210", "Bangalore")

        if customer._wallet_balance == 0:
            messages.append("PASS: Customer wallet starts at 0.")
        else:
            messages.append("CHECK: Customer wallet should start at 0.")

        customer.add_to_wallet(500)

        if customer._wallet_balance == 500:
            messages.append("PASS: Wallet top-up works.")
        else:
            messages.append("CHECK: add_to_wallet() is not updating the balance correctly.")

        before = customer._wallet_balance

        try:
            customer.add_to_wallet(-100)
        except Exception:
            pass

        if customer._wallet_balance == before:
            messages.append("PASS: Negative wallet top-up is rejected.")
        else:
            messages.append("CHECK: A negative top-up must not change the wallet balance.")

    except Exception:
        messages.append("CHECK: Customer could not be created. Review the constructor and User inheritance.")

    print("\n".join(messages))

_check_user_customer()

"""## 3. MenuItem

Create `MenuItem` with the following attributes:

- `name`
- `price`
- `is_veg`

No additional methods are required.
"""

class MenuItem:

    def __init__(self, name, price, is_veg):
        self.name = name
        self.price = price
        self.is_veg = is_veg

"""## 4. Restaurant

A school register contains student objects. In the same way, a restaurant menu contains `MenuItem` objects.

`Restaurant` requires:

- `name`
- `location`
- private `_menu`
- `add_item(menu_item)`
- `get_menu()`
- `is_open()`
"""

#@title Restaurant and MenuItem relationship { display-mode: "form" }
show("""
flowchart LR
    R[Restaurant Object]
    M1[MenuItem: Biryani]
    M2[MenuItem: Kebab]

    R --> M1
    R --> M2
""")

class Restaurant:

    def __init__(self, name, location):
        self.name = name
        self.location = location
        self._menu = []

    def add_item(self, menu_item):
        self._menu.append(menu_item)

    def get_menu(self):
        return self._menu

    def is_open(self):
        return True

"""<details>
<summary>Hint</summary>

`_menu` starts as an empty list. `add_item()` adds a `MenuItem` object to that list. For this project, `is_open()` returns `True`.

</details>
"""

# Test the menu

item1 = MenuItem("Biryani", 250, False)
item2 = MenuItem("Kebab", 180, False)

restaurant = Restaurant("Bawarchi", "MG Road")
restaurant.add_item(item1)
restaurant.add_item(item2)

print(restaurant.get_menu())

#@title Validate MenuItem and Restaurant { display-mode: "form" }

def _check_menu_restaurant():
    messages = []

    try:
        item1 = MenuItem("Biryani", 250, False)
        item2 = MenuItem("Kebab", 180, False)

        if item1.name == "Biryani" and item1.price == 250 and item1.is_veg is False:
            messages.append("PASS: MenuItem stores the required values.")
        else:
            messages.append("CHECK: MenuItem is not storing all required values correctly.")

        restaurant = Restaurant("Bawarchi", "MG Road")
        restaurant.add_item(item1)
        restaurant.add_item(item2)

        menu = restaurant.get_menu()

        if isinstance(menu, list) and item1 in menu and item2 in menu:
            messages.append("PASS: Restaurant stores MenuItem objects.")
        else:
            messages.append("CHECK: Restaurant menu should contain the MenuItem objects that were added.")

        if restaurant.is_open() is True:
            messages.append("PASS: Restaurant is open.")
        else:
            messages.append("CHECK: is_open() should return True for this project.")

    except Exception:
        messages.append("CHECK: MenuItem or Restaurant could not be tested. Review the constructors and method names.")

    print("\n".join(messages))

_check_menu_restaurant()

"""## 5. Order

An order is created when a customer places an order.

The order moves through three statuses:

`Placed` → `Accepted` → `Delivered`
"""

from IPython.display import HTML, display  # 3

!pip install mermaid-py # 1

import mermaid as md # 2
from mermaid.graph import Graph

#@title Order lifecycle { display-mode: "form" }
show("""
stateDiagram-v2
    [*] --> Placed
    Placed --> Accepted
    Accepted --> Delivered
    Delivered --> [*]
""")

"""### Order Requirements

**Attributes**

- `_order_id`, generated automatically
- `_items`, containing the selected `MenuItem` objects
- `_status`, initially `Placed`
- `_otp`, fixed at `1234`

**Methods**

- `calculate_bill()`
- `estimated_time()`
- `update_status(new_status)`
- `verify_otp(otp)`

**Billing rule**

Subtotal + 5% GST + ₹20 packaging fee.

`estimated_time()` returns `30`.
"""

# import random
# self._otp = random.randint(1000,9999)

import random

class Order:

    _counter = 1

    def __init__(self, items):
        self._order_id = Order._counter
        Order._counter += 1
        self._items = items
        self._status = "Placed"
        self._otp = random.randint(1000,9999)



    def calculate_bill(self):
        subtotal = 0
        for item in self._items:
          subtotal += item.price

        gst = subtotal * 0.05
        packaging_fees = 20

        total = subtotal + gst + packaging_fees

        return total

    def estimated_time(self):
        return 30

    def update_status(self, new_status):
      if new_status in ['Placed','Order Accepted','Processing','Cancelled','Delivered']:
        self._status = new_status

    def verify_otp(self, otp):
      if otp == self._otp:
        return True
      else:
        return False



"""<details>
<summary>Hint: order ID</summary>

Use the class counter to generate IDs such as `ORD1`, `ORD2`, and `ORD3`. Increase the counter after assigning the ID.

</details>

<details>
<summary>Hint: bill calculation</summary>

Calculate the subtotal from the price of each item in `_items`. Apply 5% GST to the subtotal, then add the ₹20 packaging fee.

</details>

<details>
<summary>Hint: status</summary>

The accepted values are `Placed`, `Accepted`, and `Delivered`.

</details>
"""

# Test the order

item1 = MenuItem("Biryani", 250, False)
item2 = MenuItem("Kebab", 180, False)

order = Order([item1, item2])

print("Bill:", order.calculate_bill())
print("Estimated time:", order.estimated_time())
print("OTP valid:", order.verify_otp(1234))

#@title Validate Order { display-mode: "form" }

def _check_order():
    messages = []

    try:
        item1 = MenuItem("Biryani", 250, False)
        item2 = MenuItem("Kebab", 180, False)
        order = Order([item1, item2])

        total = order.calculate_bill()

        if abs(total - 471.5) < 0.001:
            messages.append("PASS: Bill calculation is correct.")
        else:
            messages.append("CHECK: Order bill is off. Recheck subtotal, 5% GST, and the ₹20 packaging fee.")

        if order.estimated_time() == 30:
            messages.append("PASS: Estimated time is correct.")
        else:
            messages.append("CHECK: estimated_time() should return 30.")

        if order._status == "Placed":
            messages.append("PASS: New order starts as Placed.")
        else:
            messages.append("CHECK: A new order should start with status Placed.")

        if order.verify_otp(9999) is False:
            messages.append("PASS: Wrong OTP is rejected.")
        else:
            messages.append("CHECK: verify_otp() should return False for a wrong OTP.")

        if order.verify_otp(1234) is True:
            messages.append("PASS: Correct OTP is accepted.")
        else:
            messages.append("CHECK: verify_otp() should return True for OTP 1234.")

    except Exception:
        messages.append("CHECK: Order could not be tested. Review the constructor and required methods.")

    print("\n".join(messages))

_check_order()

"""## 6. DeliveryPartner

`DeliveryPartner` inherits from `User`.

Additional attributes:

- `vehicle`
- `is_available`, initially `True`
- `rating`, initially `0.0`

Required behaviour:

**`accept_order(order)`**
- changes the order status to `Accepted`
- makes the delivery partner unavailable

**`deliver(order, otp)`**
- verifies the OTP before completing delivery
- leaves the order as `Accepted` when the OTP is incorrect
- keeps the delivery partner unavailable when the OTP is incorrect
- changes the order status to `Delivered` when the OTP is correct
- makes the delivery partner available again after successful delivery
"""

class DeliveryPartner(User):

    def init(self, name, phone, vehicle):

        super().__init__(name,phone)

        self.vehicle = vehicle

        self.is_available = True

        self.rating = 0.0

    def notify(self, message):

        self.message = message

        print("Notification: ", message, "for delivery partner: ", self._name)

    def display_profile(self):

        print("Name: ", self._name)

        print("Phone: ", self._phone)

        print("availibility: ", self.is_available)

        print("Rating: ", self.rating)

    def accept_order(self, order):

        order.update_status("Accepted")

        self.is_available = False

    def deliver(self, order, otp):

      if order.verify_otp(otp):
        order.update_status("Delivered")
        self.is_available = True

"""## Complete System

Use the class relationships below to review how the objects interact before running the complete workflow.
"""

#@title Object interaction { display-mode: "form" }
show("""
sequenceDiagram
    participant C as Customer
    participant R as Restaurant
    participant O as Order
    participant D as DeliveryPartner

    C->>R: Select menu items
    C->>O: place_order(...)
    O-->>C: Order created

    C->>O: calculate_bill()

    D->>O: accept_order(...)
    O->>O: update_status("Accepted")

    D->>O: verify_otp(1234)
    O-->>D: OTP valid

    D->>O: update_status("Delivered")

    C->>C: notify("Order delivered")
    D->>D: notify("Order delivered")
""")

# Complete the demonstration flow.

# 1. Register customer Priya with phone 9876543210 and address Bangalore.
# 2. Register delivery partner Rajesh with vehicle Bike.
# 3. Create Bawarchi at MG Road and add Biryani and Kebab.
# 4. Top up Priya's wallet by 500, then attempt a top-up of -100.
# 5. Priya places an order for Biryani and Kebab.
# 6. Print subtotal, GST, packaging fee, total, and estimated delivery time.
# 7. Rajesh accepts the order. Try a wrong OTP, then deliver using 1234.
# 8. Notify Priya and Rajesh using notify("Order delivered").

# [Code Here]

#@title Final validation { display-mode: "form" }

def _final_project_check():
    messages = []

    try:
        customer = Customer("Priya", "9876543210", "Bangalore")
        partner = DeliveryPartner("Rajesh", "9999999999", "Bike")

        item1 = MenuItem("Biryani", 250, False)
        item2 = MenuItem("Kebab", 180, False)

        restaurant = Restaurant("Bawarchi", "MG Road")
        restaurant.add_item(item1)
        restaurant.add_item(item2)

        customer.add_to_wallet(500)

        before = customer._wallet_balance
        try:
            customer.add_to_wallet(-100)
        except Exception:
            pass

        if customer._wallet_balance == before:
            messages.append("PASS: Negative wallet top-up is rejected.")
        else:
            messages.append("CHECK: A negative wallet top-up must not change the balance.")

        order = customer.place_order(restaurant, [item1, item2])

        if isinstance(order, Order):
            messages.append("PASS: place_order() returns an Order.")
        else:
            messages.append("CHECK: place_order() should return an Order object.")

        if order in customer.order_history:
            messages.append("PASS: Order is stored in customer order history.")
        else:
            messages.append("CHECK: The created order should be added to order_history.")

        if abs(order.calculate_bill() - 471.5) < 0.001:
            messages.append("PASS: Final bill is correct.")
        else:
            messages.append("CHECK: Final bill should be 471.5.")

        partner.accept_order(order)

        if order._status == "Accepted" and partner.is_available is False:
            messages.append("PASS: Delivery partner accepts the order correctly.")
        else:
            messages.append("CHECK: accept_order() should set the order to Accepted and make the partner unavailable.")

        partner.deliver(order, 9999)

        if order._status == "Accepted" and partner.is_available is False:
            messages.append("PASS: Wrong OTP does not complete delivery.")
        else:
            messages.append("CHECK: Wrong OTP should leave the order Accepted and the partner unavailable.")

        partner.deliver(order, 1234)

        if order._status == "Delivered" and partner.is_available is True:
            messages.append("PASS: Correct OTP completes delivery.")
        else:
            messages.append("CHECK: OTP 1234 should mark the order Delivered and make the partner available.")

        import io
        import contextlib

        customer_output = io.StringIO()
        partner_output = io.StringIO()

        with contextlib.redirect_stdout(customer_output):
            customer.notify("Order delivered")

        with contextlib.redirect_stdout(partner_output):
            partner.notify("Order delivered")

        if customer_output.getvalue().strip() != partner_output.getvalue().strip():
            messages.append("PASS: Customer and DeliveryPartner notifications are different.")
        else:
            messages.append("CHECK: Customer and DeliveryPartner notifications should be visibly different.")

    except Exception:
        messages.append("CHECK: The complete project could not be tested. Review the earlier validation results.")

    print("\n".join(messages))

_final_project_check()

"""## Submission Files

The completed submission contains:

- `food_delivery.py`, all class definitions
- `demo.py`, the complete end-to-end demonstration
- `README.md`, project description and run instructions

Create the files below after the final validation passes.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile food_delivery.py
# # Paste the completed class definitions here.
# 
# # 1. User
# from abc import ABC, abstractmethod
# 
# class User(ABC):
# 
#     def __init__(self, name, phone):
#         self._name = name
#         self._phone = phone
#         self._wallet_balance = 0
# 
#     def add_to_wallet(self, amount):
#         if amount >= 0:
#           self._wallet_balance += amount
# 
#     @abstractmethod
#     def notify(self, message):
#         pass
# 
#     @abstractmethod
#     def display_profile(self):
#         pass
# 
# 
# 
# # 2. Customer
# 
# class Customer(User):
# 
#     def __init__(self, name, phone, address):
#        super().__init__(name,phone)
#        self.address = address
#        self.order_history = []
# 
#     def notify(self, message):
#         print("Notificatoin: ",message)
# 
#     def display_profile(self):
#         print("Name: ", self._name)
#         print("Phone: ", self._phone)
#         print("Wallet Balance: ", self._wallet_balance)
#         print("Address: ", self.address)
# 
#     def place_order(self, restaurant, items):
#         order = Order(items)
#         self.order_history.append(order)
#         print("Your OTP is: ",order._otp)
# 
#         return order
# 
# 
# # 3. Delivery Partner
# 
# class DeliveryPartner(User):
# 
#     def init(self, name, phone, vehicle):
# 
#         super().__init__(name,phone)
# 
#         self.vehicle = vehicle
# 
#         self.is_available = True
# 
#         self.rating = 0.0
# 
#     def notify(self, message):
# 
#         self.message = message
# 
#         print("Notification: ", message, "for delivery partner: ", self._name)
# 
#     def display_profile(self):
# 
#         print("Name: ", self._name)
# 
#         print("Phone: ", self._phone)
# 
#         print("availibility: ", self.is_available)
# 
#         print("Rating: ", self.rating)
# 
#     def accept_order(self, order):
# 
#         order.update_status("Accepted")
# 
#         self.is_available = False
# 
#     def deliver(self, order, otp):
# 
#       if order.verify_otp(otp):
#         order.update_status("Delivered")
#         self.is_available = True
# 
# 
# # 4. Menu Item
# 
# class MenuItem:
# 
#     def __init__(self, name, price, is_veg):
#         self.name = name
#         self.price = price
#         self.is_veg = is_veg
# 
# # 5. Restaurant
# 
# 
# class Restaurant:
# 
#     def __init__(self, name, location):
#         self.name = name
#         self.location = location
#         self._menu = []
# 
#     def add_item(self, menu_item):
#         self._menu.append(menu_item)
# 
#     def get_menu(self):
#         return self._menu
# 
#     def is_open(self):
#         return True
# 
# 
# # 6. Order
# 
# 
# import random
# 
# class Order:
# 
#     _counter = 1
# 
#     def __init__(self, items):
#         self._order_id = Order._counter
#         Order._counter += 1
#         self._items = items
#         self._status = "Placed"
#         self._otp = random.randint(1000,9999)
# 
# 
# 
#     def calculate_bill(self):
#         subtotal = 0
#         for item in self._items:
#           subtotal += item.price
# 
#         gst = subtotal * 0.05
#         packaging_fees = 20
# 
#         total = subtotal + gst + packaging_fees
# 
#         return total
# 
#     def estimated_time(self):
#         return 30
# 
#     def update_status(self, new_status):
#       if new_status in ['Placed','Order Accepted','Processing','Cancelled','Delivered']:
#         self._status = new_status
# 
#     def verify_otp(self, otp):
#       if otp == self._otp:
#         return True
#       else:
#         return False

# Commented out IPython magic to ensure Python compatibility.
# %%writefile demo.py
# # 1. Register customer Priya with phone 9876543210 and address Bangalore.
# # 2. Register delivery partner Rajesh with vehicle Bike.
# # 3. Create Bawarchi at MG Road and add Biryani and Kebab.
# # 4. Top up Priya's wallet by 500, then attempt a top-up of -100.
# # 5. Priya places an order for Biryani and Kebab.
# # 6. Print subtotal, GST, packaging fee, total, and estimated delivery time.
# # 7. Rajesh accepts the order. Try a wrong OTP, then deliver using 1234.
# # 8. Notify Priya and Rajesh using notify("Order delivered").
# 
# # [Code Here]
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile README.md
# # Food Delivery System
# 
# ## Project Description
# 
# [Write here]
# 
# ## Requirements
# 
# [Write here]
# 
# ## How to Run
# 
# [Write here]
#

from google.colab import files

files.download("food_delivery.py")
files.download("demo.py")
files.download("README.md")